# Generated by Django 3.2.5 on 2021-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='favorite_level',
            field=models.IntegerField(choices=[(1, 'めちゃ低い'), (2, '低い'), (3, '普通'), (4, '高い'), (5, 'めちゃ高い')], verbose_name='お気に入り度'),
        ),
        migrations.AlterField(
            model_name='closet',
            name='item_importance',
            field=models.IntegerField(choices=[(1, '捨てれる'), (2, '悩む'), (3, '普通'), (4, 'まあ大事'), (5, 'めっちゃ大事')], verbose_name='大事さ'),
        ),
        migrations.AlterField(
            model_name='closet',
            name='pricing',
            field=models.IntegerField(verbose_name='購入価格(円)'),
        ),
    ]
