# Generated by Django 3.2.5 on 2021-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_alter_closet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='アイテム画像'),
        ),
    ]
