# Generated by Django 3.2.5 on 2021-08-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_closet_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closet',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='images/closet/', verbose_name='アイテム画像'),
        ),
    ]
