# Generated by Django 3.2.5 on 2021-08-15 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False, verbose_name='アイテムNo.')),
                ('item_type', models.CharField(choices=[('jacket', '上着'), ('shirt', 'シャツ'), ('pants', 'パンツ'), ('underpants', '下着(下)'), ('undershirt', '下着(上)'), ('socks', '靴下'), ('others', 'その他')], max_length=255, verbose_name='アイテム種類')),
                ('season', models.CharField(choices=[('spring', '春'), ('summer', '夏'), ('fall', '秋'), ('winter', '冬')], max_length=10, verbose_name='季節')),
                ('occasion', models.CharField(choices=[('daily_use', '普段着'), ('work_wear', '仕事'), ('active_wear', 'よそ行き'), ('sports_wear', 'スポーツ'), ('other_use', 'その他')], max_length=30, verbose_name='シーン')),
                ('item_name', models.CharField(max_length=300, verbose_name='アイテム名称')),
                ('item_color', models.CharField(choices=[('red', '赤'), ('blue', '青'), ('green', '緑'), ('yellow', '黄'), ('purple', '紫'), ('orange', '橙'), ('black', '黒'), ('white', '白'), ('grey', '灰'), ('beige', 'ベージュ'), ('navy', 'ネイビー'), ('brown', '茶'), ('others', 'その他')], max_length=20, verbose_name='アイテム色')),
                ('item_brand', models.CharField(max_length=150, verbose_name='ブランド')),
                ('purchase_date', models.CharField(max_length=150, verbose_name='購入日')),
                ('pricing', models.IntegerField(verbose_name='購入価格(円)')),
                ('purchase_place', models.CharField(max_length=255, verbose_name='購入場所')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images/closet', verbose_name='アイテム画像')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('favorite_level', models.IntegerField(choices=[(1, 'めちゃ低い'), (2, '低い'), (3, '普通'), (4, '高い'), (5, 'めちゃ高い')], verbose_name='お気に入り度')),
                ('item_importance', models.IntegerField(choices=[(1, '捨てれる'), (2, '悩む'), (3, '普通'), (4, 'まあ大事'), (5, 'めっちゃ大事')], verbose_name='大事さ')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
