# Generated by Django 3.2.5 on 2021-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20210817_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closet',
            options={'ordering': ['closet_name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='closet',
        ),
        migrations.AddField(
            model_name='item',
            name='closet',
            field=models.ManyToManyField(to='item.Closet'),
        ),
    ]
