# Generated by Django 3.2.5 on 2021-08-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210817_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='closet',
        ),
        migrations.AddField(
            model_name='item',
            name='closet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='item.closet'),
        ),
    ]
