# Generated by Django 3.2.5 on 2021-09-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210821_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='購入日'),
        ),
    ]
