# Generated by Django 3.2.5 on 2021-09-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_purchase_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['purchase_date']},
        ),
        migrations.AlterField(
            model_name='item',
            name='favorite_level',
            field=models.IntegerField(blank=True, choices=[(1, 'めちゃ低い'), (2, '低い'), (3, '普通'), (4, '高い'), (5, 'めちゃ高い')], null=True, verbose_name='お気に入り度'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ブランド'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_color',
            field=models.CharField(blank=True, choices=[('red', '赤'), ('blue', '青'), ('green', '緑'), ('yellow', '黄'), ('purple', '紫'), ('orange', '橙'), ('black', '黒'), ('white', '白'), ('grey', '灰'), ('beige', 'ベージュ'), ('navy', 'ネイビー'), ('brown', '茶'), ('others', 'その他')], max_length=20, null=True, verbose_name='アイテム色'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_importance',
            field=models.IntegerField(blank=True, choices=[(1, '捨てれる'), (2, '悩む'), (3, '普通'), (4, 'まあ大事'), (5, 'めっちゃ大事')], null=True, verbose_name='大事さ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='購入場所'),
        ),
    ]
