# Generated by Django 3.2.5 on 2021-09-02 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='タイトル')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('requested_response', models.CharField(choices=[('express', '超急ぎ'), ('quick', '急ぎ'), ('standard', '普通'), ('slow', '急ぎません')], max_length=100, verbose_name='回答スピードの希望')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='質問日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
        ),
    ]
